  FormsWebhookLambda:
    Type: AWS::Serverless::Function
    DependsOn: FormsWebhookLogGroup
    Properties:
      FunctionName: !Sub ${AWS::StackName}-FormsWebhook
      Description: Formstack Webhook Pricing Algorithm
      Handler: index.lambda_handler
      Role: !GetAtt FormsWebhookExecutionRole.Arn
      Timeout: 60
      Runtime: python3.9
      CodeUri: formswebhook/
      Environment:
        Variables:
          APPLICATION: !Ref Application
          ENVIRONMENT: !Ref Environment
          PRICING_ALGO_DB_TABLE: !Ref PricingAlgoDynamoDBTable
          IMMUTABLE_ARCHIVE:
            Fn::Transform:
              Name: String
              Parameters:
                InputString: !Sub ${Application}-${Environment}-${DeployableUnitName}-PricingAlgoArchive
                Operation: Lower
          GREENSCREENS_SECRET:
            Fn::Transform:
              Name: String
              Parameters:
                InputString: !Sub /app/${Application}/${Environment}/${DeployableUnitName}/greenscreens-secret
                Operation: Lower
          DAT_SECRET:
            Fn::Transform:
              Name: String
              Parameters:
                InputString: !Sub /app/${Application}/${Environment}/${DeployableUnitName}/dat-secret
                Operation: Lower
          GOOGLE_API_SECRET:
            Fn::Transform:
              Name: String
              Parameters:
                InputString: !Sub /app/${Application}/${Environment}/${DeployableUnitName}/google-api-secret
                Operation: Lower
          FUEL_API_SECRET:
            Fn::Transform:
              Name: String
              Parameters:
                InputString: !Sub /app/${Application}/${Environment}/${DeployableUnitName}/fuel-api-secret
                Operation: Lower
      Tags:
        Application: !Ref Application
        Environment: !Ref Environment
        DeployableUnitName: !Ref DeployableUnitName
        GitHubBranch: !Ref GitHubBranch
        TechnicalContact: !Ref TechnicalContact
