FormsWebhookExecutionRole:
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
                Effect: Allow
                Action: sts:AssumeRole
                Principal:
                    Service: lambda.amazonaws.com
        Path: /
        Policies:
            - PolicyName: cwl-access
              PolicyDocument:
                  Version: 2012-10-17
                  Statement:
                      Effect: Allow
                      Action:
                          - logs:CreateLogStream
                          - logs:PutLogEvents
                      Resource: '*'
            - PolicyName: s3-archive-access
              PolicyDocument:
                  Version: 2012-10-17
                  Statement:
                      Effect: Allow
                      Action:
                          - s3:PutObject
                      Resource:
                          - Fn::Transform:
                                Name: String
                                Parameters:
                                    InputString: !Sub arn:${AWS::Partition}:s3:::${self:service}-${self:provider.stage}-${self:service}-PricingAlgoArchive/*
                                    Operation: Lower
            - PolicyName: ssm-access
              PolicyDocument:
                  Version: 2012-10-17
                  Statement:
                      Effect: Allow
                      Action:
                          - ssm:GetParameters
                      Resource:
                          - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/${self:service}/${self:provider.stage}/${self:service}/dat-secret
                          - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/${self:service}/${self:provider.stage}/${self:service}/greenscreens-secret
                          - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/${self:service}/${self:provider.stage}/${self:service}/google-api-secret
                          - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/${self:service}/${self:provider.stage}/${self:service}/fuel-api-secret
            - PolicyName: ses-access
              PolicyDocument:
                  Version: 2012-10-17
                  Statement:
                      Effect: Allow
                      Action:
                          - ses:SendEmail
                      Resource:
                          - !Sub arn:${AWS::Partition}:ses:${AWS::Region}:${AWS::AccountId}:identity/omnilogistics.com
            - PolicyName: DynamoDBAccessPolicy
              PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                      Effect: Allow
                      Action:
                          - dynamodb:Query
                          - dynamodb:GetItem
                          - dynamodb:PutItem
                          - dynamodb:UpdateItem
                          - dynamodb:DeleteItem
                      Resource: !GetAtt PricingAlgoDynamoDBTable.Arn
        Tags:
            Application: ${self:service}
            DeployableUnitName: ${self:service}
            GitHubBranch: ${opt:GitHubBranch, 'default-branch'}
            Environment: ${self:provider.stage}
            Technical Contact: ${opt:TechnicalContact, "tgilbertson@omnilogistics.com"}
