E2OpenSpotLambda:
  Type: AWS::Serverless::Function
  DependsOn: E2OpenSpotLogGroup
  Properties:
    FunctionName: !Sub ${AWS::StackName}-E2OpenSpot
    Description: E2Open Spot Request
    Handler: index.lambda_handler
    Role: !GetAtt E2OpenSpotExecutionRole.Arn
    Timeout: 60
    Runtime: python3.9
    CodeUri: e2open/spot
    Environment:
      Variables:
        APPLICATION: !Ref Application
        ENVIRONMENT: !Ref Environment
        PRICING_ALGO_E2OPEN_TABLE: !Ref PricingAlgoE2OpenTable       
        E2OPEN_NEW_SHIPPER_TABLE: !Ref PricingAlgoE2OpenNewShipperTable
        E2OPEN_SPOT_TABLE: !Ref PricingAlgoE2OpenSpotTable
        IMMUTABLE_ARCHIVE:
          Fn::Transform:
            Name: String
            Parameters:
              InputString: !Sub ${Application}-${Environment}-${DeployableUnitName}-PricingAlgoArchive
              Operation: Lower
        GREENSCREENS_SECRET:
          Fn::Transform:
            Name: String
            Parameters:
              InputString: !Sub /app/${Application}/${Environment}/${DeployableUnitName}/greenscreens-secret
              Operation: Lower
        DAT_SECRET:
          Fn::Transform:
            Name: String
            Parameters:
              InputString: !Sub /app/${Application}/${Environment}/${DeployableUnitName}/dat-secret
              Operation: Lower
        GOOGLE_API_SECRET:
          Fn::Transform:
            Name: String
            Parameters:
              InputString: !Sub /app/${Application}/${Environment}/${DeployableUnitName}/google-api-secret
              Operation: Lower
    Tags:
      Application: !Ref Application
      Environment: !Ref Environment
      DeployableUnitName: !Ref DeployableUnitName
      GitHubBranch: !Ref GitHubBranch
      TechnicalContact: !Ref TechnicalContact
